# Generated by Django 3.1.2 on 2021-06-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0002_auto_20210617_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
