# Generated by Django 3.1.2 on 2021-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0003_auto_20210617_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('phone_number', models.TextField()),
                ('resume_link', models.TextField()),
                ('company_name', models.TextField(blank=True, null=True)),
                ('current_ctc', models.TextField(blank=True, null=True)),
                ('expected_ctc', models.TextField(blank=True, null=True)),
                ('notice_period', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
