# Generated by Django 3.1.2 on 2021-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0004_jobapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='job_title',
            field=models.TextField(null=True),
        ),
    ]
