# Generated by Django 3.1.2 on 2021-06-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0005_jobapplications_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='email',
            field=models.TextField(null=True, unique=True),
        ),
    ]
