# Generated by Django 3.1.2 on 2021-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0007_auto_20210618_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
