# Generated by Django 3.1.2 on 2021-05-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(blank=True, default=None, max_length=6),
        ),
    ]
