# Generated by Django 3.1.2 on 2021-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20210511_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(blank=True, default='male', max_length=6),
        ),
    ]
