# Generated by Django 3.1.2 on 2021-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20210511_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='gst_number',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
