# Generated by Django 3.1.2 on 2021-05-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20210511_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
