# Generated by Django 3.1.2 on 2021-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20210511_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('login_time', models.TimeField(blank=True)),
                ('logout_time', models.TimeField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
