# Generated by Django 3.1.2 on 2021-05-11 10:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_auto_20210511_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsummary',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='loginsummary',
            name='login_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='loginsummary',
            name='logout_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
