# Generated by Django 3.1.2 on 2021-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20210511_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_token_key',
            field=models.CharField(default=None, max_length=280, null=True),
        ),
    ]
