# Generated by Django 3.1.2 on 2021-05-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_user_login_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_token_key',
            field=models.TextField(default=None, max_length=280, null=True),
        ),
    ]
