# Generated by Django 3.1.2 on 2021-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_auto_20210513_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsummary',
            name='logout_time',
            field=models.TimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
