# Generated by Django 3.1.2 on 2021-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_auto_20210513_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_token_key',
        ),
        migrations.AddField(
            model_name='loginsummary',
            name='login_token_key',
            field=models.TextField(default=None, max_length=280, null=True),
        ),
    ]
