# Generated by Django 3.1.2 on 2021-05-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_auto_20210514_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.TextField(blank=True, max_length=10, unique=True),
        ),
    ]
