# Generated by Django 3.1.2 on 2021-05-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_auto_20210517_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.TextField()),
                ('mobile', models.TextField()),
            ],
        ),
    ]
