# Generated by Django 3.1.2 on 2021-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_user_is_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='package',
            name='document_link',
            field=models.TextField(blank=True),
        ),
    ]
