# Generated by Django 3.1.2 on 2021-06-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_auto_20210602_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
