# Generated by Django 3.1.2 on 2021-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_auto_20210602_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.TextField(blank=True, max_length=3),
        ),
    ]
