# Generated by Django 3.1.2 on 2021-06-02 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, editable=False, null=True),
        ),
    ]
