# Generated by Django 3.1.2 on 2021-06-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_package_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_b2buser',
            field=models.BooleanField(default=False),
        ),
    ]
