# Generated by Django 3.1.2 on 2021-06-09 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_b2bsubuserrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('date', models.DateField(blank=True, default=datetime.date.today, editable=False, null=True)),
                ('action', models.TextField()),
                ('token_amount', models.TextField()),
            ],
        ),
    ]
