# Generated by Django 3.1.2 on 2021-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_tokenactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('dribbble_link', models.TextField(blank=True)),
                ('behance_link', models.TextField(blank=True)),
                ('facebook_link', models.TextField(blank=True)),
                ('instagram_link', models.TextField(blank=True)),
                ('twitter_link', models.TextField(blank=True)),
            ],
        ),
    ]
