# Generated by Django 3.1.2 on 2021-06-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_socialmedialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
