# Generated by Django 3.1.2 on 2021-06-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_auto_20210614_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
