# Generated by Django 3.1.2 on 2021-06-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_user_social_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_media_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
