# Generated by Django 3.1.2 on 2021-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
