# Generated by Django 3.1.2 on 2021-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_user_upi_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialinks',
            old_name='dribbble_link',
            new_name='dribble_link',
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
