# Generated by Django 3.1.2 on 2021-06-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_auto_20210614_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
