# Generated by Django 3.1.2 on 2021-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_auto_20210615_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_city',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='company_country',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='company_phone',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='company_phone_code',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='company_state',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='company_zipcode',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
