# Generated by Django 3.1.2 on 2021-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_auto_20210618_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
