# Generated by Django 3.1.2 on 2021-07-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_user_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_billing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='type_of_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
