# Generated by Django 3.1.2 on 2021-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_cover_image', models.TextField(null=True)),
                ('title', models.TextField(null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
