# Generated by Django 3.1.2 on 2021-06-16 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.date.today, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
