# Generated by Django 3.1.2 on 2021-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_management', '0002_auto_20210616_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
