# Generated by Django 3.1.2 on 2021-07-01 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_management', '0003_auto_20210616_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
