# Generated by Django 3.1.2 on 2021-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0021_auto_20200902_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='max_checkout_items_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
