# Generated by Django 3.1.2 on 2021-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0129_add_product_types_and_attributes_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
