# Generated by Django 3.1.2 on 2021-06-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_auto_20210621_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
