# Generated by Django 3.1.2 on 2021-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0132_auto_20210621_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='input_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multi Select'), ('text', 'Text')], default='dropdown', max_length=50),
        ),
    ]
