# Generated by Django 3.1.2 on 2021-06-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_auto_20210621_1547'),
        ('product', '0130_auto_20210621_0916'),
    ]

    operations = [
    ]
