# Generated by Django 3.1.2 on 2021-06-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0134_merge_20210622_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='region',
            field=models.CharField(blank=True, choices=[('all_region', 'All Region'), ('asia', 'Asia'), ('north america', 'North America'), ('south america', 'South America'), ('europe', 'Europe'), ('africa', 'Africa'), ('ocenia', 'Ocenia')], default='all_region', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='m', max_length=255, null=True),
        ),
    ]
