# Generated by Django 3.1.2 on 2021-06-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20210616_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion_banner',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion_banner',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
